name: Go
on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - '*'

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: go setup 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: checkout
      uses: actions/checkout@v1

    - name: dependencies
      run: go get -v -t -d ./...

    - name: build
      run: go build -v ./...
    
    - name: test
      run: go test -v ./...
      env:
        private_key: ${{ secrets.private_key }}
        application_id: ${{ secrets.application_id }}
        installation_id: ${{ secrets.installation_id }}